### ISSUE TITLE
Feature Request: Change network settings

### ISSUE THREAD

**Issue by muzzol** [AdamLaurie/sjcam#2]
I'm not sure if someone tried to change network address so you can monitorize several camera streams with a single computer (without changing from one wifi to another).

I'd like to see this implemented.

**Comment by muzzol** [comment]
sorry, I don't know how I missed the IP option.

I close the Issue.

**Comment by tamasharasztosi** [comment]
> I'm not sure if someone tried to change network address so you can monitorize several camera streams with a single computer (without changing from one wifi to another).
> 
> I'd like to see this implemented.

Is there an option to change WIFI setting to Client mode so the camera could connect to a WIFI router?
